<?php
namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{


    public function checkPseudo($pseudo)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('COUNT(u.idUtilisateur)')
            ->where("u.nmPseudo = '". $pseudo. "'");
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function checkMail($email)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('COUNT(u.idUtilisateur)')
            ->where("u.nmAdresseMail = '". $email. "'");
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function checkUser($email, $password)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->where("u.nmAdresseMail = '". $email. "'")
            ->andWhere("u.nmMdp = '". $password ."'");
        return $qb->getQuery()->execute();
    }

    public function search($user, $idSession)
    {
        $user = strtolower($user);

        $qb = $this->createQueryBuilder('u');


        $orModule = $qb->expr()->orX();
        $orModule->add($qb->expr()->like("LOWER(u.nmPseudo)", $qb->expr()->literal('%'.$user.'%')));
        $orModule->add($qb->expr()->like("LOWER(u.nmPrenom)", $qb->expr()->literal('%'.$user.'%')));
        $orModule->add($qb->expr()->like("LOWER(u.nmNom)", $qb->expr()->literal('%'.$user.'%')));

        $qb->where("u.idUtilisateur != ".$idSession);
        $qb->andWhere($orModule);
        $qb->groupBy('u.idUtilisateur');

        return $qb->getQuery()->execute();
    }
}